name: CI

on:
    push:
        branches:
            - "master"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - run: npm install
            - run: npx vsce package
            - uses: actions/upload-artifact@v2
              with:
                  name: bundle
                  path: "*.vsix"

    publish:
        runs-on: ubuntu-latest
        needs: build
        environment: Production
        if: success()
        steps:
            - uses: actions/download-artifact@v2
            - run: npx vsce publish --packagePath $(find . -iname *.vsix)
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
