name: CI

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run test

  publish:
    name: Publish to marketplace
    runs-on: ubuntu-latest
    environment: Production
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - name: Publish to Open VSX Registry
        id: publishToOpenVSX
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPENVSX_PAT }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
