name: CI

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - run: npm install
            - run: npx vsce package
            - uses: actions/upload-artifact@v2
              with:
                  name: bundle
                  path: "*.vsix"

    publish:
        runs-on: ubuntu-latest
        needs: build
        environment: Production
        if: success()
        steps:
            - name: Publish to Open VSX Registry
              id: publishToOpenVSX
              uses: HaaLeo/publish-vscode-extension@v1
              with:
                  pat: ${{ secrets.OPENVSX_PAT }}
            - name: Publish to Visual Studio Marketplace
              uses: HaaLeo/publish-vscode-extension@v1
              with:
                  pat: ${{ secrets.VSCE_PAT }}
                  registryUrl: https://marketplace.visualstudio.com
                  extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
