name: Test

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      ANDREAS_TEST: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: npm --color install
      - name: Test create vsix
        id: createVsix
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: none
          packagePath: out
          dryRun: true
      - run: npm --color run test
