name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: read
  issues: write

jobs:
  run-tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      ANDREAS_TEST: true

    steps:
      # - name: Checkout repository
      # uses: actions/checkout@v7

      # - name: Set up Node.js
      #   uses: actions/setup-node@v7
      #   with:
      #     node-version-file: .nvmrc
      #     cache: npm

      # - name: Install dependencies
      #   run: npm --color ci

      # - name: Build
      #   run: npm --color run build

      # - name: Run lint (Linux)
      #   run: npm --color run lint
      #   if: runner.os == 'Linux'

      # - name: Run tests (Linux)
      #   run: xvfb-run -a npm --color run test:ci
      #   if: runner.os == 'Linux'

      # - name: Run tests (Windows, MacOS)
      #   run: npm --color run test:ci
      #   if: runner.os != 'Linux'

      - name: Update PR labels
        uses: AndreasArvidsson/gh-pr-labeler@main
        if: runner.os == 'Linux'
