name: Test

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-tests:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      ANDREAS_TEST: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: npm --color install
      - run: npm --color run compile
      - run: xvfb-run -a npm --color run test:ci
        if: runner.os == 'Linux'
      - run: npm --color run test:ci
        if: runner.os != 'Linux'
